### PR TITLE
CPDNPQ-1523 Course Start Page

### PR DESCRIPTION
**Pull request by javier-npq**
### Context

Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-1523

### CODE REVIEW

**Comment by dalcJ** [comment]
@javier-npq 
Content change, on the Start page, first bullet point: 

Change from `starting in February 2024` to `starting before April 2024`
Screenshot 2024-01-16 at 10 50 39

**Comment by dalcJ** [comment]
@javier-npq 

Content change, Check your answers page, on the Course start row. 

Change from `February 2024` to `Before April 2024`

Screenshot 2024-01-16 at 10 48 17

**Comment by dalcJ** [comment]
@javier-npq 
Content change on the funding outcome pages. 
From `starting in February 2024.` to `starting before April 2024.`

Screenshot 2024-01-16 at 11 24 23

**Comment by dalcJ** [comment]
@javier-npq on the 'in review' funding outcome pages is it possible to add the NPQ name like all the other funding outcome pages have? So it could be like this: 

Screenshot 2024-01-16 at 11 28 36

**Comment by dalcJ** [comment]
@javier-npq content change on course start date question

First sentence changed to: `NPQ start dates vary by provider and course, but they usually start every February and October.`

Second sentence changed to: `Registrations are currently open for courses starting before April 2024.`

Question changed to: `Do you want to start a course before April 2024?`

Screenshot 2024-01-16 at 11 56 47

**Comment by dalcJ** [comment]
@javier-npq Apologies, there a few additional content changes. 

On course start date question:

First sentence changed to: `NPQ start dates are usually every February and October.`

Add new second sentence: `Early headship coaching offer start dates vary by provider and are throughout the year.`

The rest remains as is:

Screenshot 2024-01-16 at 20 08 54

**Comment by dalcJ** [comment]
For this one, just need to make the 'b' for 'Before' uppercase


> @javier-npq
> 
> Content change, Check your answers page, on the Course start row.
> 
> Change from `February 2024` to `Before April 2024`
> 
> Screenshot 2024-01-16 at 10 48 17

**Review by slawosz — APPROVED** [review]

**Comment by dalcJ** [comment]
@javier-npq  Sorry, just found one more funding outcome page that needs `starting before April 2024.` to the end of the first sentence:

Screenshot 2024-01-19 at 10 46 19

Screenshot 2024-01-19 at 10 49 56

**Comment by javier-npq** [comment]
> @javier-npq Sorry, just found one more funding outcome page that needs `starting before April 2024.` to the end of the first sentence:
> 
> Screenshot 2024-01-19 at 10 46 19
> 
> Screenshot 2024-01-19 at 10 49 56

@dalcJ I've addressed the requested changes. Can you please check now.

**Comment by dalcJ** [comment]
@javier-npq all looks good, thank you

**Pull request merged**
