### PR TITLE
Signpost users to get certificates in user account pages

### PR DESCRIPTION
**Pull request by javier-npq**
### Context
Updated context on multiple pages
### Ticket
https://dfedigital.atlassian.net/browse/CPDNPQ-1385
### Changes proposed in this pull request

- Add build point on start page(`check your course outcome, if you have completed your course`)
- Added translations of course outcomes in en.yml
- Used new details of outcome in required pages

### CODE REVIEW

**Comment by FMooi** [comment]
Screenshot 2023-11-15 at 10 27 18
The links to the qualification service are not appearing as expected in the review app

**Comment by dalcJ** [comment]
@javier-npq text on this should be 'Get your NPQ certificate through the [Access your teaching qualifications](https://access-your-teaching-qualifications.education.gov.uk/qualifications/start) service.'

Screenshot 2023-11-16 at 16 04 59

**Comment by dalcJ** [comment]
Everything else looks good :)

**Comment by dalcJ** [comment]
Thanks @javier-npq all good from me.

**Review by slawosz — APPROVED** [review]

**Pull request merged**
