### PR TITLE
CPDNPQ-1344 Improve signposting for users to create another registration

### PR DESCRIPTION
**Pull request by javier-npq**
### Context

Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-1344

### Changes proposed in this pull request

Some UI changes mentioned in the ticket.
'Register for a national professional qualification' button in header now imitates the 'Register for another NPQ' button. 
Spec fixes

### Failed feature specs screenshots

If any of the feature specs would fail, there will be page on the wiki with all
failures:

https://github.com/DFE-Digital/npq-registration/wiki/

### CODE REVIEW

**Review by slawosz — APPROVED** [review]

**Comment by dalcJ** [comment]
The page title (at the top of the browser tab, above the address) isn't showing as updated. 

- For account page, it should say 'Your NPQ registrations - National professional qualifications account'

> Screenshot 2023-10-06 at 11 48 50

- For registration details pages, it should say 'Your registration details - National professional qualifications account'

> Screenshot 2023-10-06 at 11 48 45

**Comment by dalcJ** [comment]
Apologies, the part on the ticket about this was really unclear. These headings shouldn't have been updated. Please can they be reverted to what they were: 
Screenshot 2023-10-06 at 11 53 23
Screenshot 2023-10-06 at 12 42 08

**Comment by javier-npq** [comment]
> Apologies, the part on the ticket about this was really unclear. These headings shouldn't have been updated. Please can they be reverted to what they were: Screenshot 2023-10-06 at 11 53 23 Screenshot 2023-10-06 at 12 42 08

No Problem. I've reverted the changes. If we use these texts in title then the suffix "- Register for a national professional qualification" will always show at the end. Please let me know if that would be ok?

**Comment by dalcJ** [comment]
All looks good, thanks @javier-npq

**Pull request merged**
