### PR TITLE
Update work details after registration

### PR DESCRIPTION
**Pull request by pmanrubia**
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-1387

### Context

1. As a user I want to review all the answers I have submitted so I can ensure they are all correct.
2. As a UCD team we want the registration details pages to be easy to understand and consistent with the check answers pages.

### CODE REVIEW

**Comment by dalcJ** [comment]
@pmanrubia some weird stuff is showing up: 

Screenshot 2023-12-05 at 17 04 55

**Comment by dalcJ** [comment]
@pmanrubia When the user has answered the question ‘How is your NPQ being paid for?’ - the label should display as  ‘Course funding’ instead of ‘How is your NPQ being paid for?’

Screenshot 2023-12-05 at 20 13 43

**Comment by dalcJ** [comment]
@pmanrubia when a user has selected 'No' to  ‘Do you work in England' question. The answer to the question answered the question ‘How is your NPQ being paid for?’ is not showing. This should appear under 'Scholarship funding' row and have the label 'Course funding'.  
 
Screenshot 2023-12-05 at 20 15 51

**Comment by dalcJ** [comment]
@pmanrubia When the question ‘Enter your or your employer’s Ofsted URN’ is answered. The row is currently just showing the URN. But this should show the name and address of the workplace. 

Current: 
Screenshot 2023-12-05 at 20 23 54

Should be: 
Screenshot 2023-12-05 at 20 25 15

**Comment by dalcJ** [comment]
@pmanrubia The label 'ITT PRovider' should have lowercase 'PR', so 'ITT provider'

Screenshot 2023-12-05 at 20 34 01

**Comment by dalcJ** [comment]
@pmanrubia When the user selects the course Early headship coaching offer and is not eligible for funding, so they answer the 'How is your ECHO being paid for?' question. There are 2 rows showing. Changes to make:

- The bottom row shouldn't display. 
- The row label 'How is your ECHO being paid for?' should be 'Course funding' 

Screenshot 2023-12-05 at 20 39 12

**Comment by dalcJ** [comment]
@pmanrubia When the user selects the course Early headship coaching offer. The row 'First 5 years of headship' is not displaying accurate info 

- When 'Headteacher' = No, the 'First 5 years of headship' row should not appear 
- When I select No to 'First 5 years of headship' it displayed as Yes. 


Screenshot 2023-12-05 at 20 43 54
Screenshot 2023-12-05 at 20 39 47

**Comment by dalcJ** [comment]
@pmanrubia just tested maths NPQ. When the user chooses 'Yes' to the first maths question (Have you taken at least one year of the primary maths Teaching for Mastery programme?), it is not displaying correctly on the registration details page: 

Screenshot 2023-12-07 at 09 57 28

**Comment by dalcJ** [comment]
> @pmanrubia The label 'ITT PRovider' should have lowercase 'PR', so 'ITT provider'
> 

For this the P in 'provider' should also be lowercase. I've just noticed this is also incorrect on the check answers page. Could we also change that at the same time? 

registration details page:
Screenshot 2023-12-07 at 10 07 35

check answers page:
Screenshot 2023-12-07 at 10 08 22

**Comment by dalcJ** [comment]
@pmanrubia I've retested all now

**Comment by dalcJ** [comment]
@javier-npq just one thing that is now showing up. The ITT provider is showing a string rather than the name: 

Screenshot 2024-01-18 at 14 48 11

**Comment by dalcJ** [comment]
@javier-npq all looks good, I'm happy for this to be merged if everyone else has checked.

**Review by slawosz — APPROVED** [review]

**Pull request merged**
