### PR TITLE
Add Mermaid support to API guidance

### PR DESCRIPTION
**Pull request by ethax-ross**
[Jira-3592](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?assignee=712020%3A5b5839dc-e4d6-4df5-9dd6-627cc49fe345&selectedIssue=CPDLP-3592)

### Context

We want to be able to render Mermaid sequence diagrams in the API guidance.

### Changes proposed in this pull request

- Add Mermaid support to API guidance

Add `mermaid.js` pcakge and initialize on all pages. Override the default style to make it more in keeping with the rest of our website.

### Guidance to review

We wanted to style notes in different colours, but this doesn't appear to be possible. Similarly, the text was start/ending right on the note border and there's not an easy way to add padding globally. A work around is to use `#nbsp;` before/after the text to give additional spacing.

Example test page:

```
# Test Page

A test page to demonstrate a Mermaid process diagram:

<div class="mermaid">
sequenceDiagram
    participant teacher as Participant
    participant provider as Provider
    participant assessor as Assessor
    participant dfe as DfE
    participant tra as TRA

    Note over teacher,tra: Assessment completion and submission
    Note over teacher: #nbsp;Do course assessment#nbsp;
    teacher->>+provider: Submit assessment to provider
    Note over provider: #nbsp;Receive assessment#nbsp;
    provider->>+assessor: Send assessment to Tribal (third-party assessor)
    Note over teacher,tra: Assessment review
    Note over assessor: #nbsp;Review assessment#nbsp;
    assessor->>+provider: Send assessment result to provider
    Note over provider: #nbsp;Receive outcome from assessor#nbsp;
    Note over teacher,tra: Processing outcomes
    Note over provider: #nbsp;Inform delivery partners of outcome#nbsp;
    provider->>+dfe: Send completion declaration (pass/fail) to DfE via API
    Note over dfe: #nbsp;Check completion declaration#nbsp;
    Note over dfe: #nbsp;Update participant record#nbsp;
    dfe->>+tra: Send passed outcomes to the Teaching Regulation Agency (TRA)
    Note over tra: #nbsp;Process certificate#nbsp;
    tra->>+dfe: Send course outcome to participant with link for them to get their certificate
    Note over dfe: #nbsp;Add outcome to participant assessor#nbsp;
    dfe->>+teacher: Get NPQ certificate
    Note over teacher: #nbsp;NPQ course complete#nbsp;
</div>

Some more text around it
```

Screenshot 2024-09-18 at 14 36 40

### CODE REVIEW

**Review by leandroalemao — COMMENTED** [review]
It's working here locally but text in the diagram is a bit too small.. there's no way of zoom it as Github does? maybe increase the font size and apparently the theme and options can be changed using this before 
```
<div class="mermaid">
%%{
  init: {
    'theme': 'forest'
  }
}%%
sequenceDiagram
    participant teacher as Participant
...
```

**Comment by cwrw** [comment]
@ethax-ross and myself had a look at the small font, it's because the generated mermaid diagram adjusts to the max width. Since the image itself is quite large we are getting the small text. We discussed adding pan/zoom options but those will probably be extra work we bring in. We can maybe chat to Mark and if he's ok for now we can bring in further tickets for this, what do you think?

**Comment by peteryates** [comment]
Maybe if the diagram's not put in a 2/3 column, and is in a full-width column instead, zooming wouldn't be quite as necessary?

**Comment by cwrw** [comment]
> Maybe if the diagram's not put in a 2/3 column, and is in a full-width column instead, zooming wouldn't be quite as necessary? I think it'll automatically scale up as it fills the extra space.

Yea that's true I tested this yesterday it didn't look great 🤔 
Screenshot 2024-09-19 at 11 28 08

**Comment by peteryates** [comment]
Ah, fair. Maybe something like [mermaid viewer](https://github.com/newmo-oss/mermaid-viewer) could just be dropped in?

**Comment by cwrw** [comment]
> Ah, fair. Maybe something like [mermaid viewer](https://github.com/newmo-oss/mermaid-viewer) could just be dropped in?

cool, I'll add that as an option to the ticket to tackle zooming, thanks!

**Pull request merged**
