### PR TITLE
Closed registration

### PR DESCRIPTION
**Pull request by slawosz**

### CODE REVIEW

**Review by javier-npq — APPROVED** [review]

**Comment by dalcJ** [comment]
On account page, this blocks needs more space above the heading. For the breakpoint around 640px, have margin 20px. Then screenwidths >640px 40px.

Screenshot 2024-03-28 at 09 03 35

**Comment by dalcJ** [comment]
When signed in and then using the 'Register for a national professional qualification' link in the header. It should go to the registration closed page (the one shown on the right of this image): 

Screenshot 2024-03-28 at 09 20 41

**Comment by dalcJ** [comment]
On the request email updates question page. The privacy notice text should appear above the  button 

Screenshot 2024-03-28 at 09 23 37

**Comment by dalcJ** [comment]
When using either of these 'change' links on registration details pages:
Screenshot 2024-03-28 at 09 27 02

They should go to the page shown on the right (currently going to the one shown on the left): 
Screenshot 2024-03-28 at 09 26 57

**Comment by dalcJ** [comment]
When trying to access any URL that is isn't available while the service is closed, it should show the content on the right : 

Screenshot 2024-03-28 at 09 36 07

**Comment by dalcJ** [comment]
When a user is answering the request email question but doesn't give an answer, the error message should say 'You must choose an option to continue' 

Screenshot 2024-03-28 at 09 25 38

**Pull request merged**
